stages:
    - test-python
    - pypi

services:
  - name: mendhak/http-https-echo:latest
    alias: testhost

python3_6_unit_test:
  image: seriallab/python3.6dev
  stage: test-python
  script:
  - apt-get install -y git
  - export PYTHONPATH=$PYTHONPATH:$CI_PROJECT_DIR
  - pip install -r requirements_test.txt
  - coverage run runtests.py
  - coverage report -m
  - coverage html
  artifacts:
    paths:
      - htmlcov/

pages:
  image: seriallab/python3.6dev
  stage: build-docs
  script:
  - export PYTHONPATH=$PYTHONPATH:$CI_PROJECT_DIR
  - pip install sphinx recommonmark sphinx_rtd_theme pygments ipython
  - pip install -r requirements_test.txt
  - pip install -r requirements.txt
  - cd docs/
  - make docs
  - mv docs/_build/html/ public/
  artifacts:
      paths:
      - public
      expire_in: 1h

deploy_pypi:
    image: seriallab/python3.6dev
    stage: pypi
    environment:
      name: deployment
      url: https://pypi.org/
    script:
      - echo "[distutils]" >> ~/.pypirc
      - echo "index-servers = " >> ~/.pypirc
      - echo "[pypi]" >> ~/.pypirc
      - echo "username=$PYPI_USER" >> ~/.pypirc
      - echo "password=$PYPI_PASSWORD" >> ~/.pypirc
      - python setup.py check sdist bdist_wheel upload
      - rm ~/.pypirc
    only:
      - tags
